---
- name: Detect the user the tasks will run as
  ansible.builtin.command:
    cmd: id -u
  changed_when: false
  register: user_id

- name: Disable and stop the podman-auto-update timer
  ansible.builtin.systemd:
    name: podman-auto-update.timer
    scope: "{{ omit if user_id.stdout == '0' else 'user' }}"
    enabled: false
    state: stopped
  when: pau_event_expr == ""

- name: Set up the podman-auto-update timer
  when: pau_event_expr != ""
  block:
    - name: Ensure the podman-auto-update.timer.d directory exists and with the right permissions
      ansible.builtin.file:
        path: >-
          {{ '/etc/systemd/system' if user_id.stdout == '0'
          else '~/.config/systemd/user' }}/podman-auto-update.timer.d
        state: directory
        mode: "0755"

    - name: Create the podman-auto-update.timer.d/override.conf file
      ansible.builtin.template:
        src: pau-override.conf.j2
        dest: >-
          {{ '/etc/systemd/system' if user_id.stdout == '0'
          else '~/.config/systemd/user' }}/podman-auto-update.timer.d/override.conf
        mode: "0644"
      register: override_file

    - name: Issue systemctl daemon-reload to pick up config changes
      ansible.builtin.systemd:
        daemon_reload: true
        scope: "{{ omit if user_id.stdout == '0' else 'user' }}"
      when: override_file is changed # noqa: no-handler

    - name: Enable the podman-auto-update timer
      ansible.builtin.systemd:
        name: podman-auto-update.timer
        scope: "{{ omit if user_id.stdout == '0' else 'user' }}"
        enabled: true

    - name: Ensure the podman-auto-update timer is started (if config didn't change)
      ansible.builtin.systemd:
        name: podman-auto-update.timer
        scope: "{{ omit if user_id.stdout == '0' else 'user' }}"
        state: started
      when: override_file is not changed

    - name: Restart the podman-auto-update timer (if config is changed)
      ansible.builtin.systemd:
        name: podman-auto-update.timer
        scope: "{{ omit if user_id.stdout == '0' else 'user' }}"
        state: restarted
      when: override_file is changed # noqa: no-handler
